# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='city',
            field=models.CharField(max_length=250),
        ),
    ]
